name: ala_kosan
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.0.0
  google_nav_bar: ^5.0.3
  image_picker: ^0.7.2
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
