name: ala_kosan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0+1
  google_fonts: ^2.0.0
  google_nav_bar: ^5.0.3
  image_picker: ^0.7.2
  intl: ^0.17.0
  lottie: ^1.0.1
  pinput: ^1.2.0
  provider: ^5.0.0
  shared_preferences: ^2.0.3
  shimmer: ^1.1.2
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.7+1

flutter_native_splash:
  color: '#FF5252'
  image: assets/images/logo_app.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
